import type { ReportData, TestEntryResult } from './types';

export function buildReportHtml(data: ReportData): string {
  const entriesJson = JSON.stringify(data.entries.map((e) => ({
    trackId: e.trackId,
    type: e.type,
    success: e.success,
    error: e.error,
    renderTimeMs: e.renderTimeMs,
    issueCount: e.validationIssues.length + e.coreValidationErrors.length,
    warningCount: e.coreValidationWarnings.length,
  })));

  return /* html */ `<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>huh test report</title>
<style>
${REPORT_CSS}
</style>
</head>
<body>
<div class="report">
  ${buildHeader(data)}
  ${buildSummary(data)}
  <div class="toolbar">
    <input type="text" id="search" placeholder="Search trackId..." />
    <select id="filter-type">
      <option value="">All Types</option>
      <option value="TOAST">TOAST</option>
      <option value="MODAL">MODAL</option>
      <option value="PAGE">PAGE</option>
    </select>
    <select id="filter-status">
      <option value="">All Status</option>
      <option value="pass">Pass</option>
      <option value="fail">Fail</option>
      <option value="warning">Warning</option>
    </select>
  </div>
  <div class="entries" id="entries">
    ${data.entries.map(buildEntryCard).join('\n')}
  </div>
  ${buildFooter(data)}
</div>
<script>
var entriesMeta = ${entriesJson};
${REPORT_JS}
</script>
</body>
</html>`;
}

function buildHeader(data: ReportData): string {
  return `
  <header class="header">
    <h1>huh test report</h1>
    <p class="meta">${data.device.name} (${data.device.width}x${data.device.height}) &middot; ${data.mode} mode &middot; ${data.generatedAt}</p>
  </header>`;
}

function buildSummary(data: ReportData): string {
  return `
  <div class="summary">
    <div class="summary-card total"><span class="num">${data.totalEntries}</span><span class="label">Total</span></div>
    <div class="summary-card pass"><span class="num">${data.passCount}</span><span class="label">Pass</span></div>
    <div class="summary-card fail"><span class="num">${data.failCount}</span><span class="label">Fail</span></div>
    <div class="summary-card warn"><span class="num">${data.warningCount}</span><span class="label">Warning</span></div>
  </div>`;
}

function buildEntryCard(entry: TestEntryResult): string {
  const statusClass = !entry.success
    ? 'fail'
    : entry.validationIssues.length > 0 || entry.coreValidationErrors.length > 0
      ? 'fail'
      : entry.coreValidationWarnings.length > 0
        ? 'warning'
        : 'pass';

  const statusLabel = statusClass === 'fail' ? 'FAIL' : statusClass === 'warning' ? 'WARN' : 'PASS';

  const imgTag = entry.screenshotBase64
    ? `<img src="data:image/png;base64,${entry.screenshotBase64}" alt="${entry.trackId} screenshot" loading="lazy" />`
    : '<div class="no-screenshot">No screenshot</div>';

  const issues = [
    ...entry.coreValidationErrors.map((e) => `<li class="issue-error">${escapeHtml(e.message)}</li>`),
    ...entry.validationIssues.filter((i) => i.severity === 'error').map((i) => `<li class="issue-error">${escapeHtml(i.message)}</li>`),
    ...entry.coreValidationWarnings.map((w) => `<li class="issue-warning">${escapeHtml(w.message)}</li>`),
    ...entry.validationIssues.filter((i) => i.severity === 'warning').map((i) => `<li class="issue-warning">${escapeHtml(i.message)}</li>`),
  ];

  const issuesHtml = issues.length > 0
    ? `<ul class="issues">${issues.join('')}</ul>`
    : '';

  return `
    <div class="entry-card ${statusClass}" data-track-id="${escapeHtml(entry.trackId)}" data-type="${escapeHtml(entry.type)}" data-status="${statusClass}">
      <div class="entry-header">
        <span class="badge ${statusClass}">${statusLabel}</span>
        <span class="track-id">${escapeHtml(entry.trackId)}</span>
        <span class="type-badge">${escapeHtml(entry.type)}</span>
        <span class="render-time">${entry.renderTimeMs}ms</span>
      </div>
      <div class="entry-body">
        <div class="screenshot">${imgTag}</div>
        ${entry.error ? `<div class="error-msg">${escapeHtml(entry.error)}</div>` : ''}
        ${issuesHtml}
      </div>
    </div>`;
}

function buildFooter(data: ReportData): string {
  return `
  <footer class="footer">
    <p>Generated by <strong>huh test</strong> &middot; ${data.totalEntries} entries &middot; ${data.generatedAt}</p>
  </footer>`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// ── Report CSS ──

const REPORT_CSS = `
* { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: #f0f2f5;
  color: #1a1a2e;
  line-height: 1.5;
}

.report {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem 1.5rem;
}

.header {
  margin-bottom: 1.5rem;
}

.header h1 {
  font-size: 1.75rem;
  font-weight: 700;
}

.header .meta {
  color: #666;
  font-size: 0.875rem;
  margin-top: 0.25rem;
}

.summary {
  display: flex;
  gap: 1rem;
  margin-bottom: 1.5rem;
}

.summary-card {
  flex: 1;
  background: #fff;
  border-radius: 10px;
  padding: 1rem;
  text-align: center;
  box-shadow: 0 1px 3px rgba(0,0,0,0.08);
}

.summary-card .num {
  display: block;
  font-size: 2rem;
  font-weight: 700;
}

.summary-card .label {
  font-size: 0.75rem;
  text-transform: uppercase;
  color: #888;
}

.summary-card.pass .num { color: #22c55e; }
.summary-card.fail .num { color: #ef4444; }
.summary-card.warn .num { color: #f59e0b; }

.toolbar {
  display: flex;
  gap: 0.75rem;
  margin-bottom: 1.5rem;
  flex-wrap: wrap;
}

.toolbar input, .toolbar select {
  padding: 0.5rem 0.75rem;
  border: 1px solid #ddd;
  border-radius: 6px;
  font-size: 0.875rem;
  background: #fff;
}

.toolbar input { flex: 1; min-width: 200px; }

.entries {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(360px, 1fr));
  gap: 1rem;
}

.entry-card {
  background: #fff;
  border-radius: 10px;
  overflow: hidden;
  box-shadow: 0 1px 3px rgba(0,0,0,0.08);
  border-left: 4px solid #22c55e;
}

.entry-card.fail { border-left-color: #ef4444; }
.entry-card.warning { border-left-color: #f59e0b; }

.entry-header {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1rem;
  border-bottom: 1px solid #f0f0f0;
}

.badge {
  display: inline-block;
  padding: 0.15rem 0.5rem;
  border-radius: 4px;
  font-size: 0.7rem;
  font-weight: 700;
  text-transform: uppercase;
}

.badge.pass { background: #dcfce7; color: #16a34a; }
.badge.fail { background: #fee2e2; color: #dc2626; }
.badge.warning { background: #fef3c7; color: #d97706; }

.track-id {
  font-weight: 600;
  font-size: 0.875rem;
}

.type-badge {
  font-size: 0.7rem;
  padding: 0.1rem 0.4rem;
  background: #f0f2f5;
  border-radius: 3px;
  color: #555;
}

.render-time {
  margin-left: auto;
  font-size: 0.75rem;
  color: #999;
}

.entry-body {
  padding: 1rem;
}

.screenshot img {
  width: 100%;
  border-radius: 6px;
  border: 1px solid #eee;
}

.no-screenshot {
  padding: 2rem;
  text-align: center;
  color: #ccc;
  background: #fafafa;
  border-radius: 6px;
}

.error-msg {
  margin-top: 0.5rem;
  padding: 0.5rem;
  background: #fff1f2;
  color: #dc2626;
  border-radius: 4px;
  font-size: 0.8rem;
}

.issues {
  list-style: none;
  margin-top: 0.5rem;
}

.issues li {
  padding: 0.25rem 0.5rem;
  font-size: 0.8rem;
  border-radius: 3px;
  margin-bottom: 0.25rem;
}

.issue-error { background: #fff1f2; color: #dc2626; }
.issue-warning { background: #fffbeb; color: #d97706; }

.footer {
  margin-top: 2rem;
  padding-top: 1rem;
  border-top: 1px solid #e5e7eb;
  text-align: center;
  color: #999;
  font-size: 0.8rem;
}

/* Hidden by filter */
.entry-card.hidden { display: none; }
`;

// ── Report JS (filtering/search) ──

const REPORT_JS = `
(function() {
  var searchInput = document.getElementById('search');
  var filterType = document.getElementById('filter-type');
  var filterStatus = document.getElementById('filter-status');
  var cards = document.querySelectorAll('.entry-card');

  function applyFilters() {
    var search = searchInput.value.toLowerCase();
    var type = filterType.value;
    var status = filterStatus.value;

    cards.forEach(function(card) {
      var trackId = card.getAttribute('data-track-id').toLowerCase();
      var cardType = card.getAttribute('data-type');
      var cardStatus = card.getAttribute('data-status');

      var matchSearch = !search || trackId.indexOf(search) !== -1;
      var matchType = !type || cardType === type;
      var matchStatus = !status || cardStatus === status;

      if (matchSearch && matchType && matchStatus) {
        card.classList.remove('hidden');
      } else {
        card.classList.add('hidden');
      }
    });
  }

  searchInput.addEventListener('input', applyFilters);
  filterType.addEventListener('change', applyFilters);
  filterStatus.addEventListener('change', applyFilters);
})();
`;
